const BASE_URL = process.env.SMOKE_BASE_URL || "http://localhost:4173";
const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

let token = "";

async function api(path, options = {}) {
  const response = await fetch(`${BASE_URL}${path}`, {
    headers: {
      "content-type": "application/json",
      ...(token ? { "x-session-token": token } : {})
    },
    ...options
  });
  const text = await response.text();
  const data = text ? JSON.parse(text) : {};
  if (!response.ok) {
    throw new Error(`${path} -> ${response.status}: ${data.detail || data.error || text}`);
  }
  return data;
}

async function register(name) {
  const emailPrefix = name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const data = await api("/api/auth/register", {
    method: "POST",
    body: JSON.stringify({
      email: `${emailPrefix}.${suffix}@example.com`,
      password: "SmokeTest123!",
      name
    })
  });
  return data;
}

async function main() {
  const health = await api("/api/health");
  assert(health.ok, "health ok");

  const userA = await register("Smoke A");
  token = userA.token;
  assert(userA.user?.id, "user A created");

  const me = await api("/api/me");
  assert(me.user?.id === userA.user.id, "session loads /api/me");

  const search = await api("/api/search?query=dark");
  assert(search.items?.length, "search returns items");
  const item = search.items.find((entry) => entry.mediaType === "tv") || search.items[0];

  const added = await api("/api/library", {
    method: "POST",
    body: JSON.stringify({ mediaType: item.mediaType, tmdbId: item.tmdbId, status: "planned" })
  });
  assert(added.item?.user, "library add works");

  const liked = await api(`/api/library/${item.mediaType}/${item.tmdbId}`, {
    method: "PATCH",
    body: JSON.stringify({ favorite: true })
  });
  assert(liked.item?.user?.favorite === true, "favorite works");

  const seen = await api(`/api/library/${item.mediaType}/${item.tmdbId}/seen`, { method: "POST" });
  assert(seen.item?.user, "mark seen works");

  const list = await api("/api/lists", {
    method: "POST",
    body: JSON.stringify({ name: "Smoke list", description: "Generated by smoke test" })
  });
  assert(list.list?.id, "list create works");

  const listUpdated = await api(`/api/lists/${list.list.id}/items`, {
    method: "POST",
    body: JSON.stringify({ mediaType: item.mediaType, tmdbId: item.tmdbId })
  });
  assert(listUpdated.list?.items?.length, "list item add works");

  const userB = await register("Smoke B");
  token = userA.token;
  const friends = await api("/api/friends", {
    method: "POST",
    body: JSON.stringify({ friendId: userB.user.id })
  });
  assert(friends.social?.friends?.some((entry) => entry.friendId === userB.user.id), "friend add works");

  const profile = await api("/api/profile", {
    method: "PATCH",
    body: JSON.stringify({ name: "Smoke A Updated", settings: { bio: "Smoke profile" } })
  });
  assert(profile.user?.name === "Smoke A Updated", "profile update works");

  console.log("Smoke tests passed");
}

function assert(value, message) {
  if (!value) {
    throw new Error(`Assertion failed: ${message}`);
  }
  console.log(`ok - ${message}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
